name: Updates translation progress

on:
  push:
    branches:
      - rewrite

jobs:
  update-translation-progress-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Check for translation errors and progress
        run: npm run check-translation-jsons

      - name: Update translation progress issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue edit 1 --body-file ./translation-progress.md
